# Dockerfile
# docker login --username=davemateer 
# docker build -t davemateer/redirectnginx .
# docker push davemateer/redirectnginx

# ACR
# docker login davem.azurecr.io -u davem -p TYPEITHERE
# docker build -t davem.azurecr.io/redirectnginx .
# docker push davem.azurecr.io/redirectnginx

#FROM nginx:1.13.12
FROM nginx:1.14.0
COPY nginx.conf /etc/nginx

